const express = require('express')
const db = require('./db')
const cors = require('cors')
const bodyParser = require('body-parser')
const logger = require(`morgan`)
const everythingController = require('./controllers/everythingController')
const PORT = process.env.PORT || 3001

const app = express()
app.use(logger('dev'))
app.use(bodyParser.json())
app.use(cors())
app.use(express.json())
app.listen(PORT, () => {
  console.log(`Express server listening on port ${PORT}`)
})

app.get(`/`, (req, res) => {
    res.send("You have set up your server.js")
})

app.get(`/Creators`, everythingController.getAllCreator)
app.get('/Creators/:id', everythingController.getCreatorById)
app.get('/Creators/name/:userName', everythingController.getCreatorByName)
app.post(`/Creators`, everythingController.createCreator)
app.put('/Creators/:id', everythingController.updateCreator)
app.delete('/Creators/:id', everythingController.deleteCreator)
app.get(`/Character`, everythingController.getAllCharacters)
app.get(`/Story`, everythingController.getAllStory)
app.get('/Character/:id', everythingController.getCharacterById)
app.get('/Story/:id', everythingController.getStoryById)
app.post(`/Character`, everythingController.createCharacter)
app.put('/Character/:id', everythingController.updateCharacter)
app.delete('/Character/:id', everythingController.deleteCharacter)
app.post(`/Story`, everythingController.createStory)
app.put('/Story/:id', everythingController.updateStory)
app.delete('/Story/:id', everythingController.deleteStory)
